config/routes.rb
Rails.application.routes.draw do
  get 'static_page/show'
	get 'log/new'
	get 'sessions/new'
	root to: 'static_page#show'
	get '/secretpage', to: 'secret_page#show'
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
   VALID_LAST_NAME_REGEX = /^[a-zA-Z0-9\-_]{0,40}$/
   validates :last_name, presence: true, length: { maximum: 50 }
   VALID_FIRST_NAME_REGEX = /^[a-zA-Z0-9\-_]{0,40}$/
   validates :first_name, presence: true, length: { maximum: 50 }
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, length: { maximum: 255 },
                           format: { with: VALID_EMAIL_REGEX },
                           uniqueness: { case_sensitive: false }
   has_secure_password
   validates :password, presence: true

 # Returns the hash digest of the given string.
 def User.digest(string)
   BCrypt::Password.create(string, cost: cost)
   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                 BCrypt::Engine.cost
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/secret_page_controller.rb
class SecretPageController < ApplicationController

before_action :require_login

 def show
 end

 private

     def require_login
     unless logged_in?
       flash[:info] = "You must be logged in to access this section"
       redirect_to '/login' # halts request cycle
     end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
 	end

	 def create
	     user = User.find_by(email: params[:session][:email].downcase)
	   if user && user.authenticate(params[:session][:password])
	     # Log the user in and redirect to the user's show page.
	    log_in user
	    redirect_to user
	   else
	     # Create an error message.
	     flash.now[:info] = 'invaliiiid'
	     render 'new'
	   end

	 end

	 def destroy
	    log_out
	    redirect_to('/login')
	end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:create, :new]
  before_action :check_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

   def check_user
   if current_user != @user
     redirect_to('/')
     flash[:info] =  "Sorry, This Profile belongs to someone else !"
   end
 end
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end

  def require_login
    unless logged_in?
      flash[:info] = "You must be logged in to access this section"
      redirect_to new_user_path# halts request cycle
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/secret_page_helper.rb
module SecretPageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
   session[:user_id] = user.id
 end

	def current_user
	   if session[:user_id]
	     @current_user ||= User.find_by(id: session[:user_id])
	   end
	end

 def logged_in?
     !current_user.nil?
 end

 def log_out
   session.delete(:user_id)
   @current_user = nil
 end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
   <nav class="navbar navbar-light" style="background-color: #aef88e; justify-content: space-around;">
       <a class="navbar-brand" href="/">Home</a>

       <% if logged_in? %>
  <%= link_to "Aller tchao!", logout_path, method: :delete %>
 <a id="homebtn1" class="btn btn-lg btn-info" href="/secretpage" style="width: 300px;"> regarde par la !</a>
 <a id="homebtn1" class="btn btn-lg btn-info" href="/users" style="width: 300px;"> Tema tous les fdp...</a>
 <% else %>
 <a id="homebtn1" class="btn btn-lg btn-info" href="/login" style="width: 300px;"> log toi mon brave !</a>

<% end %>

   </nav>
 </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
    <%= render 'layouts/header' %>
    <div><%= flash[:info] %></div>
    <%= yield %>
  </body>
</html>

app/views/secret_page/show.html.erb
<h1>PrivatePage</h1>

<a id="homebtn1" class="btn btn-lg btn-success" href="https://www.youtube.com/watch?v=ShRwY0hKyHg" style="width: 300px;"> Prends-en de la graine !</a>

app/views/static_page/show.html.erb
<h1>salut</h1>

<% if logged_in? %>
 <a id="homebtn1" class="btn btn-lg btn-success" href="/secretpage" style="width: 300px;"> on te dit tout !</a>
<% else %>
 <a id="homebtn1" class="btn btn-lg btn-info" href="/login" style="width: 300px;"> log toi fdp !</a>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong class="table-danger" >First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong class="table-danger" >Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong class="table-danger" >Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong class="table-danger" >Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>